# Worker de avisos por correo de xdanx.cl (ver src/index.js)
name = "avisos-xdanx"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = false
routes = [{ pattern = "avisos.xdanx.cl", custom_domain = true }]

# Revisa Kick cada minuto
[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "AVISOS"
id = "79533ad0a450481fadd6735a78f4a8e5"
